### ISSUE TITLE
incorrect directory detection

### ISSUE THREAD

**Issue by abenkovskii** [Felger/AutoPruner#7]
On windows line "Squad/Parts/FuelTank/xenonTank" prunes both inline and radial xenon tanks although radial tank is placed in "xenonTankRadial" folder not in "xenonTank".

**Comment by Felger** [comment]
That makes sense.  I likely need to change it to "xenonTank/." to get the regex working, it's getting a false match on the xenonTank part of xenonTankRadial directory.

**Comment by abenkovskii** [comment]
it should probably be automatically applied to all patches in the program rather than in the config because this behavior is not obvious enough.

**Comment by abenkovskii** [comment]
Imagine situation: mod X in version v has a folder <obsolete_part_name> under it's parts directory and the same mod in version v + 1 in addition to <some_obsolete_part_name> folder also has a folder named <obsolete_part_name><useful_part_suffix>. If prune list was created before update it is likely to prune both folders.

**Comment by Felger** [comment]
Making sure I understand your request.  As it stands now, an entry of
FASA/Apollo
Will also prune the unintended directory of:
FASA/Apollo72

However, if we update this to:
FASA/Apollo/.

It will not prune the contents of FASA/Apollo72, which is the expected behavior.  I'll put out some updated prnls for that sometime soon.

**Comment by abenkovskii** [comment]
No I think this is the code bug. Do you know that not only you are writing prnls?

**Comment by Felger** [comment]
Maybe I don't understand the issue, can you post a prnl to pastebin or something where you're having issues, along with a description of what's happening so I can take a look?

**Comment by abenkovskii** [comment]
It is not an error in the concrete prnl (otherwise I could easily fix it myself) it is a bug in your code that may cause some problems if someone (modmaker for example) forgets to add '/' at the end of the line that describes directory path.

**Comment by Felger** [comment]
I think I understand, though it'd help to have an example of what you're talking about to make sure.

If so, though, it's expected behavior.  Here's how autopruner figures out if it should prune a given file:  

1. Read in the prunelist specified by the user, store in an array.
2. Work through the GameData folder procedurally
3. For each relevant file (certain directories files are excluded, like ATM) get the full path, like this:  
    /users/abenkovskii/apps/KerbalSpaceProgram/GameData/Squad/Parts/Engines/mainsail.cfg
4. Compare that file to each item in the prunelist.
5. If a match is found anywhere in the string, prune the item (append .pruned)

So, if you have a prunelist item like this:
    /Squad/Parts/FuelTank/XenonTank
And two files like this:
    /users/abenkovskii/apps/KerbalSpaceProgram/GameData**/Squad/Parts/FuelTank/XenonTank**Radial.cfg
    /users/abenkovskii/apps/KerbalSpaceProgram/GameData**/Squad/Parts/FuelTank/XenonTank**.cfg
Then you'll get a match on each of them due to the bolded area matching both. To avoid this, you must be specific:
    /Squad/Parts/FuelTank/XenonTank.cfg
Will only match the second item, but no the first.  Now, this exposes a minor bug, in that regex will interpret the . as a wildcard, so it's possible to match to something like this:
    /users/abenkovskii/apps/KerbalSpaceProgram/GameData/Squad/Parts/FuelTank/XenonTankacfg
But unlikely.

**Comment by abenkovskii** [comment]
1) Now I found the place in the code where it checks if file marches (it wasn't easy because I don't know perl).
2) Currently it searches not for mach anywhere in the string but only for mach from start of the path relative to GameData.
3) regex will NOT interpret the . as a wildcard because it is inside a literal sequence (enclosed with \Q and \E).

**Comment by abenkovskii** [comment]
Then can someone explain why this behavior is chosen?

**Comment by Felger** [comment]
I should read my own changelog, forgot I sanitized the prunelist input to the regex last update.

The behavior is chosen because it's a simple matching method, doesn't require accounting for a ton of edge cases.  If you want to prune a directory, you just need to add an explicity "/" to the end of your prnl entry.

If you have an alternative method, feel free to submit a PR or pseudo-code for how it ought to be handled and I'll consider it.

Regardless, I'm still hoping for an example to show the behavior that you'd like the script to avoid.  I'm still not sure I understand how you're hoping for it to behave...

**Comment by abenkovskii** [comment]
pseudo-code:
function prune_dir (path dir_path, bool prune_all):
    for file in dir_path:
        if prune_all or file name exactly matches one of patterns:
          rename file
    for directory in dir_path:
        prune_dir(directory, prune_all or directory exactly matches one of patterns)
Am I missing something? What edge cases you are talking about?

**Comment by Felger** [comment]
Functionally, that's no different from simply adding a "/" to the end of a directory name in a PRNL now.  

Also, if you want to prune all, we don't need a separate check.  Just input something that'll match every filepath, like 000_Global does with "/".

**Comment by abenkovskii** [comment]
1. relying on correct user (prnl creator in this case) input without checking it isn't a good practice. Is it?
2. bool prune_all is for recursive call.

**Comment by Felger** [comment]
One way or another we're relying on correct user input.  Making a specific check for directory name matching doesn't change that.  Adding a closing "/" to signify a directory name is fairly common practice.

It basically boils down to, "I like it the way it is" so I'm disinclined to change it.

**Working as intended**

**Comment by abenkovskii** [comment]
Well... It actually works reasonably fine. Plus I don't know Perl. Plus I ended up not using autopruner for my main mod build (ActiveTextureManagement is awesome). So I'll close this issue.
